apiVersion: configuration.konghq.com/v1beta1
kind: KongUpstreamPolicy
metadata:
  name: consistent-hashing
  #needs to be the same namespace as the target service
  namespace: smplapp
spec:
  #roundRobin, consistent-hashing, least-connections, latency
  algorithm: consistent-hashing
  slots: 500
  #none, input(consumer, ip, path), header, cookie, cookiePath, queryArg, uriCapture
  hashOn:
    #header: X-Forwarded-For
    #header: x-lb
    #cookie: lb
    #cookiePath: /
    input: ip
  hashOnFallback:
    # don't dupulicate the hashOn value
    #input: ip
    header: X-Forwarded-For

  healthchecks:
    active:
      healthy:
        interval: 5
        successes: 3
      httpPath: /healthcheck
      type: http
      unhealthy:
        httpFailures: 1
        interval: 5
    passive:
      healthy:
        successes: 3
      unhealthy:
        httpFailures: 3
