bases:
  - "./environments.yaml"

releases:
  - name: smplapp
    namespace: smplapp
    createNamespace: false
    chart: ./phpfpm-chart
    #version: 0.1.0
    values:
      #- "./env-merge.yaml.gotmpl"
      - "./values.yaml"
      - "./env/values-{{ .Environment.Name }}.yaml"

