# Default values for phpfpm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

###############################################################################
# names overrides
nameOverride: ""
fullnameOverride: ""
## auto 'podname' prefix addition to volume name & configmaps name
#  to noduplicate the names in multi pods in one namespace
volumesAutoPrefix: true

###############################################################################
# If HPA enabled, replicaCount would not be used.
#
replicaCount: 3

###############################################################################
# HPA
#
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1


###############################################################################
# containers
#
phpfpm:
  name: php-fpm
  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000
  image:
    repository: harbor.dh1.div1.opendoor.local/smplapp-a/app-otel
    tag: "latest"
    pullPolicy: Always
  env:
    tz: "GMT-9"
    otel_php_excluded_urls: "healthz,healthcheck"
    otel_php_detectors: "all"
    otel_php_internal_metrics_enabled: "true"
    otel_php_autoload_enabled: "true"
    otel_service_name: "smplapp-app"
    otel_traces_exporter: "otlp"
    otel_metrics_exporter: "none"
    otel_exporter_otlp_protocol: "grpc"
    otel_exporter_otlp_endpoint: "http://otel-collector.tracing.svc.cluster.local:4317"
    #otel_exporter_otlp_protocol: "http/json"
    #otel_exporter_otlp_protocol: "http/protobuf"
    #otel_exporter_otlp_endpoint: "http://otel-collector.tracing.svc.cluster.local:4318"
    #otel_exporter_otlp_traces_endpoint: "http://otel-collector.tracing.svc.cluster.local:4317/v1/traces"
    #otel_exporter_otlp_metrics_endpoint: "http://otel-collector.tracing.svc.cluster.local:4317/v1/metrics"
    otel_logs_exporter: "none"
    otel_propagators: "baggage,tracecontext"
  extraEnv: []

  ports: []

  livenessProbe: {}
  readinessProbe: {}
  startupProbe: {}

  resources:
    requests:
      memory: "128Mi"
      cpu: "10m"
    limits:
      memory: "1024Mi"
      cpu: "2000m"

  volumeMounts:
  - name: fpm-shared
    mountPath: /var/run/php-fpm
  - name: appstore-logs
    mountPath: /var/www/webapp/writable/logs
  - name: appstore-debugbar
    mountPath: /var/www/webapp/writable/debugbar

  extraVolumeMounts: []

nginx:
  name: nginx
  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  image:
    repository: harbor.dh1.div1.opendoor.local/smplapp-a/web-otel
    tag: "latest"
    pullPolicy: Always
  env:
    nginx_envsubst_filter: "^NGINX_.*|^OTEL_.*|^FASTCGI_.*"
    nginx_listen_port: "8080"
    nginx_proxy_read_timeout: "300"
    nginx_proxy_connect_timeout: "300"
    nginx_proxy_send_timeout: "300"
    otel_trace: "on"
    otel_endpoint: "otel-collector.tracing.svc.cluster.local:4317"
    otel_service_name: "smplapp-nginx"
    otel_trace_context: "propagate"
    fastcgi_read_timeout: "300"
    fastcgi_params_addfile: "fastcgi_params-codeigniter-development"
  extraEnv: []

  ports:
  - name: http-port
    containerPort: 8080

  livenessProbe:
    httpGet:
      path: /healthcheck
      port: http-port
      httpHeaders:
      - name: X-B3-Sampled
        value: "0"
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3
  readinessProbe:
    httpGet:
      path: /healthcheck
      port: http-port
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
  startupProbe:
    httpGet:
      path: /healthcheck
      port: http-port
    failureThreshold: 6
    periodSeconds: 10

  resources:
    requests:
      memory: "64Mi"
      cpu: "10m"
    limits:
      memory: "128Mi"
      cpu: "500m"

  volumeMounts:
  - name: fpm-shared
    mountPath: /var/run/php-fpm

  extraVolumeMounts: []

sidecar:
  fluentBit:
    enabled: true
    name: fluent-bit
    securityContext: {}
      # capabilities:
      #   drop:
      #   - ALL
      # readOnlyRootFilesystem: true
      # runAsNonRoot: true
      # runAsUser: 1000
 
    image:
      repository: harbor.dh1.div1.opendoor.local/hub.docker.com/fluent/fluent-bit
      #tag: "3.1.10-debug"
      tag: "3.1.10"
      pullPolicy: IfNotPresent
    env:
      tz: "GMT-9"
    extraEnv: []

    ports: []

    livenessProbe: {}
    readinessProbe: {}
    startupProbe: {}

    resources:
      requests:
        memory: "64Mi"
        cpu: "10m"
      limits:
        memory: "128Mi"
        cpu: "100m"

    volumeMounts:
    - name: appstore-logs
      mountPath: /appstore/writable/logs
    - name: fluentbit-config
      mountPath: /fluent-bit/etc
    extraVolumeMounts: []

  helper:
    enabled: true
    name: delete-logs
    securityContext: {}
      # capabilities:
      #   drop:
      #   - ALL
      # readOnlyRootFilesystem: true
      # runAsNonRoot: true
      # runAsUser: 1000

    image:
      repository: harbor.dh1.div1.opendoor.local/hub.docker.com/ubuntu
      tag: "24.04"
      pullPolicy: IfNotPresent
    env:
      tz: "GMT-9"
    extraEnv: []

    command: ["bash", "-c", "--"]
    args: ["while :; do sh /appstore/deletelogs/log_compress.sh; sleep 300; done;"]

    ports: []

    livenessProbe: {}
    readinessProbe: {}
    startupProbe: {}

    resources:
      requests:
        memory: "32Mi"
        cpu: "10m"
      limits:
        memory: "32Mi"
        cpu: "50m"

    volumeMounts:
    - name: appstore-logs
      mountPath: /appstore/writable/logs
    - name: appstore-debugbar
      mountPath: /appstore/writable/debugbar
    - name: delete-logs-scripts
      mountPath: /appstore/deletelogs

    extraVolumeMounts: []

  phpExporter:
    enabled: true
    name: php-fpm-exporter
    securityContext: {}
    image:
      repository: docker.io/hipages/php-fpm_exporter
      tag: "1.0"
      pullPolicy: IfNotPresent
    env:
      php_fpm_web_listen_address: ":9253"
      php_fpm_web_telemetry_path: "/metrics"
      php_fpm_scrape_uri: "unix:///var/run/php-fpm/php-fpm.sock;/phpfpm_status"
      php_fpm_fix_process_count: "false"
      php_fpm_log_level: "info"
    extraEnv: []
    ports:
    - name: metrics-9253
      containerPort: 9253
      protocol: TCP
    livenessProbe:
      httpGet:
        path: /
        port: metrics-9253
    redinessProbe:
      httpGet:
        path: /
        port: metrics-9253
    startupProbe: {}
    resources:
      requests:
        memory: "32Mi"
        cpu: "10m"
      limits:
        memory: "128Mi"
        cpu: "50m"
    service:
      portname: http-9253
      type: ClusterIP
      port: 9253
      targetPort: 9253
      protocol: TCP
    volumeMounts:
    - name: fpm-shared
      mountPath: /var/run/php-fpm
    extraVolumeMounts: []

    serviceMonitor:
      enabled: true
      additionalLabels: {}
      #namespace: monitoring
      interval: 30s
      scrapeTimeout: 10s
    prometheusRule:
      enabled: false
      additionalLabels: {}
      namespace: ""
      rules: []


# Additional volumes on the output Deployment definition.
volumes:
- name: fpm-shared
  emptyDir: {}
- name: appstore-logs
  emptyDir: {}
- name: appstore-debugbar
  emptyDir: {}
- name: fluentbit-config
  configMap:
    name: cm-fluentbit-config
- name: delete-logs-scripts
  configMap:
    name: cm-delete-logs-scripts
    items:
    - key: log_compress.sh
      path: log_compress.sh
      mode: 0755
    - key: log_compress.conf
      path: log_compress.conf
      mode: 0644

extraVolumes: []

###############################################################################
# pods
#
podAnnotations: {}
podLabels:
  version: v1

podSecurityContext: {}
  # fsGroup: 2000


nodeSelector: {}

affinity:
  podAntiAffinity:
    #requiredDuringSchedulingIgnoredDuringExecution:
    #- labelSelector:
    #    matchExpressions:
    #    - key: app
    #      operator: In
    #      values:
    #      - smplapp-phpfpm
    #  topologyKey: "kubernetes.io/hostname"
    #preferredDuringSchedulingIgnoredDuringExecution:
    #- weight: 100
    #  podAffinityTerm:
    #    labelSelector:
    #      matchExpressions:
    #      - key: app
    #        operator: In
    #        values:
    #        - smplapp-phpfpm
    #    topologyKey: "kubernetes.io/hostname"

topologySpreadConstraints:
- maxSkew: 1
  topologyKey: kubernetes.io/hostname
  whenUnsatisfiable: ScheduleAnyway
  labelSelector:
    matchLabels:
      app: smplapp-phpfpm

tolerations: []


###############################################################################
# ConfigMaps
#
configMaps:
- name: cm-fluentbit-config
  data:
    fluent-bit.conf: |-
      [SERVICE]
        Config_Watch      On
        Flush             1
        Grace             5
        Daemon            Off
        Log_Level         info
        Parsers_File      /fluent-bit/etc/parsers.conf
        HTTP_Server       Off
        Hot_Reload        On
        Storage.Path      /appstore/fb-storage
        Storage.Backlog.Mem_Limit 100MB
      
      [INPUT]
        Name              tail
        Buffer_Max_Size   64k
        Mem_Buf_Limit     10MB
        Path              /appstore/writable/logs/*.log,/appstore/writable/logs/**/*.log,/appstore/writable/logs/**/**/*.log
        Path_Key          filepath
        #Parser            codeigniter_timeparser
        Tag               smplapp
        Ignore_Older      2d
        Db                /appstore/logs.db
      
      [FILTER]
        Name              parser
        Match             *
        Key_Name          filepath
        #Parser            codeigniter_timeparser
        Parser            dirname_extractor
        Preserve_Key      On
        Reserve_Data      On
      
      [OUTPUT]
        Name              stdout
        Match             *
      [OUTPUT]
        Name              loki
        Match             *
        Host              loki-gateway.logbase.svc.cluster.local
        port              80
        #labels            job=fluentbit,app=smplapp,dirname=$dirname,filepath=$filepath
        labels            job=fluentbit,app=smplapp,dirname=$dirname
        auto_kubernetes_labels On
        line_format       json
        Retry_Limit       False
      
    parsers.conf: |-
      [PARSER]
        Name              dirname_extractor
        Format            regex
        # dirnam only
        Regex             ^(?<dirname>.*/)[^/]*$
      [PARSER]
        Name              codeigniter_timeparser
        #Format            regex
        #Regex             ^(?<time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}).*$
        #Time_Key          time
        #Time_Format       %Y-%m-%d %H:%M:%S

- name: cm-delete-logs-scripts
  data:
    log_compress.conf: |-
      # Configuration file for log_compress.sh
    log_compress.sh: |-
      #!/bin/bash
      # delete logs older than 1 days
      #find /appstore/writable -type f -mtime +1 -exec rm -f {} \;
      find /appstore/writable/debugbar -type f -mmin +60 -exec rm -f {} \;
      find /appstore/writable/logs -type f -mtime +1 -exec rm -f {} \;
      exit $?

extraConfigMaps: []


###############################################################################
# Service
#  multiple services can be defined
  # multiple service is definable
  # to avoid kong-gateway-controller's upstreampolicy confilict,
  # split the service-name by gateway
service:
  default: # default service.name is releaseName
    enabled: false
    nameOverride: # service-name override
    annotations: {}
    portname: http-8080
    type: ClusterIP
    port: 8080
    targetPort: 8080
    protocol: TCP
    externalTrafficPolicy: ""
    loadBalancerIP: ""
    loadBalancerClass: ""
    sessionAffinity: None
  glb: # extra service, default service-name suffix
    enabled: false
    nameOverride: # service-name override
    annotations: {}
    portname: http-8080
    type: ClusterIP
    port: 8080
    targetPort: 8080
    protocol: TCP
    externalTrafficPolicy: ""
    loadBalancerIP: ""
    loadBalancerClass: ""
    sessionAffinity: None

###############################################################################
# GatewayAPI's HttpRoutes
#
gateways:
  enabled: false
  httproutes:
    httproutename-suffix:
      enabled: false
      nameOverride: # gateway-name override
    #  annotations:
    #  parentRefs:
    #  hostnames:
    #  rules

###############################################################################
# Custom Resources
#  current supported resources: KongPlugin, KongUpstreamPolicy
customResources:
  KongUpstreamPolicy:
    enabled: false
    policies:
      policyname-suffix:
        enabled: false
        nameOverride: # policy-name override
        spec: {}

  KongPlugin:
    enabled: false
    plugins:
      pluginname-suffix:
        enabled: false
        nameOverride: # plugin-name override
        plugin: opentelemetry
        config: {}

