{{- $rootval := . -}}
{{- $prefix := "" -}}
  {{- $prefix = include "phpfpm.fullname" . -}}
{{- if .Values.gateways.enabled }}
{{- range $name, $route := .Values.gateways.httproutes }}
  {{- if $route.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  {{- if $route.nameOverride }}
  name: {{ $route.nameOverride }}
  {{- else }}
  name: {{ printf "%s-%s" $prefix $name }}
  {{- end }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "phpfpm.labels" $rootval | nindent 4 }}
  {{- with $route.annotations }}
  annotations:
    {{- toYaml . | nindent 6 }}
  {{- end }}
spec:
  {{- with $route.parentRefs }}
  parentRefs:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- with $route.hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- with $route.rules }}
  rules:
    {{- toYaml . | nindent 4 }}
  {{- end -}}
  {{- end }}

{{- end }}
{{- end }}

