---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "phpfpm.fullname" . }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "phpfpm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.portname }}
    {{- with .Values.sidecar.phpExporter.enabled }}
    - port: {{ $.Values.sidecar.phpExporter.service.port }}
      targetPort: {{ $.Values.sidecar.phpExporter.service.targetPort }}
      protocol: {{ $.Values.sidecar.phpExporter.service.protocol }}
      name: {{ $.Values.sidecar.phpExporter.service.portname }}
    {{- end}}
  {{ with .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  {{ with .Values.service.loadBalancerClass }}
  loadBalancerClass: {{ . }}
  {{- end }}
  {{ with .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .Values.service.sessionAffinity }}
  sessionAffinity: {{ . }}
  {{- end }}
  selector:
    {{- include "phpfpm.selectorLabels" . | nindent 4 }}
