{{/* name rename */}}
{{- $rootval := . -}}
{{- $releaseNamespace := .Release.Namespace -}}
{{- $prefix := "" -}}
  {{- $prefix = include "phpfpm.fullname" . -}}
{{- $services := .Values.service -}}
{{- range $name, $manifest := $services }}
  {{- if $manifest.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  {{- if and (eq $name "default") (not $manifest.nameOverride) }}
  name: {{ include "phpfpm.fullname" $rootval }}
  {{- else }}
    {{- if $manifest.nameOverride }}
  name: {{ $manifest.nameOverride }}
    {{- else }}
  name: {{ printf "%s-%s" $prefix $name }}
    {{- end }}
  {{- end }}
  namespace: {{ $releaseNamespace }}
  {{- with $manifest.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "phpfpm.labels" $rootval | nindent 4 }}
spec:
  type: {{ $manifest.type }}
  ports:
    - port: {{ $manifest.port }}
      targetPort: {{ $manifest.targetPort }}
      protocol: {{ $manifest.protocol }}
      name: {{ $manifest.portname }}
    {{- with and $.Values.sidecar.phpExporter.enabled  (eq $name "default") }}
    - port: {{ $.Values.sidecar.phpExporter.service.port }}
      targetPort: {{ $.Values.sidecar.phpExporter.service.targetPort }}
      protocol: {{ $.Values.sidecar.phpExporter.service.protocol }}
      name: {{ $.Values.sidecar.phpExporter.service.portname }}
    {{- end}}
  {{ with $manifest.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  {{ with $manifest.loadBalancerClass }}
  loadBalancerClass: {{ . }}
  {{- end }}
  {{ with $manifest.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with $manifest.sessionAffinity }}
  sessionAffinity: {{ . }}
  {{- end }}
  selector:
    {{- include "phpfpm.selectorLabels" $rootval | nindent 4 }}
  {{- end }}
{{- end }}

