{{- if and .Values.sidecar.phpExporter.enabled .Values.sidecar.phpExporter.prometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "phpfpm.fullname" . }}
{{- with .Values.sidecar.phpExporter.prometheusRule.namespace }}
  namespace: {{ . }}
{{- end }}
  labels:
{{ include "phpfpm.labels" . | indent 4 }}
  {{- if .Values.sidecar.phpExporter.prometheusRule.additionalLabels }}
{{ toYaml .Values.sidecar.phpExporter.prometheusRule.additionalLabels | indent 4 }}
  {{- end }}
spec:
{{- with .Values.sidecar.phpExporter.prometheusRule.rules }}
  groups:
    - name: {{ include "phpfpm.name" $ }}
      rules: {{ tpl (toYaml .) $ | nindent 8 }}
{{- end }}
{{- end }}
