apiVersion: apps/v1
kind: Deployment
metadata:
  name: smplapp1
  namespace: smplapp
  labels:
    app: smplapp1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: smplapp1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: smplapp1
    spec:
      containers:
      - name: smplapp-app
        image: harbor.dh1.div1.opendoor.local/smplapp/app-otel:latest
        #imagePullPolicy: IfNotPresent
        imagePullPolicy: Always
        env:
        - name: TZ
          value: GMT-9
        - name: OTEL_PHP_EXCLUDED_URLS
          value: "healthz,healthcheck"
        - name: OTEL_PHP_DETECTORS
          value: all
        - name: OTEL_PHP_INTERNAL_METRICS_ENABLED
          value: "true"
        - name: OTEL_PHP_AUTOLOAD_ENABLED
          value: "true"
        - name: OTEL_SERVICE_NAME
          value: smplapp-app
        - name: OTEL_TRACES_EXPORTER
          value: otlp
        - name: OTEL_METRICS_EXPORTER
          value: none
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: grpc
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://otel-collector.tracing.svc.cluster.local:4317
        #- name: OTEL_EXPORTER_OTLP_PROTOCOL
        #  #value: http/json
        #  value: http/protobuf
        #- name: OTEL_EXPORTER_OTLP_ENDPOINT
        #  value: http://otel-collector.tracing.svc.cluster.local:4318
        #- name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
        #  value: http://otel-collector.tracing.svc.cluster.local:4317/v1/traces
        #- name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
        #  value: http://otel-collector.tracing.svc.cluster.local:4317/v1/metrics
        - name: OTEL_LOGS_EXPORTER
          value: none
        - name: OTEL_PROPAGATORS
          value: "baggage,tracecontext"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "1024Mi"
            cpu: "2000m"
        volumeMounts:
        - name: fpm-shared
          mountPath: /var/run/php-fpm
        - name: appstore-logs
          mountPath: /var/www/webapp/writable/logs
        - name: appstore-debugbar
          mountPath: /var/www/webapp/writable/debugbar

      - name: smplapp-nginx
        image: harbor.dh1.div1.opendoor.local/smplapp/nginx-otel:latest
        #imagePullPolicy: IfNotPresent
        imagePullPolicy: Always
        env:
        - name: NGINX_ENVSUBST_FILTER
          value: "^OTEL_.*|^FASTCGI_PARAMS_ADDFILE"
        - name: OTEL_TRACE
          value: "on"
        - name: OTEL_ENDPOINT
          value: otel-collector.tracing.svc.cluster.local:4317
        - name: OTEL_SERVICE_NAME
          value: smplapp-nginx
        - name: OTEL_TRACE_CONTEXT
          value: propagate
        - name: FASTCGI_PARAMS_ADDFILE
          value: fastcgi_params-codeigniter-development
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: liveness-port
          containerPort: 8080
        volumeMounts:
        - name: fpm-shared
          mountPath: /var/run/php-fpm

        # probes
        livenessProbe:
          httpGet:
            path: /index.php
            port: liveness-port
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /index.php
            port: liveness-port
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
        startupProbe:
          httpGet:
            path: /index.php
            port: liveness-port
          failureThreshold: 6
          periodSeconds: 10

      # application-log shipping sidecar
      - name: fluent-bit
        #image: cr.fluentbit.io/fluent/fluent-bit:3.0.7
        image: harbor.dh1.div1.opendoor.local/hub.docker.com/fluent/fluent-bit:3.0.7-debug
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: GMT-9
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
          - name: appstore-logs
            mountPath: /appstore/writable/logs
          - name: smplapp1-fb-config
            mountPath: /fluent-bit/etc

      # application-log housekeeping sidecar
      - name: smplapp1-delete-logs
        image: harbor.dh1.div1.opendoor.local/hub.docker.com/ubuntu:24.04
        env:
        - name: TZ
          value: GMT-9
        resources:
          requests:
            memory: "32Mi"
            cpu: "20m"
          limits:
            memory: "32Mi"
            cpu: "50m"
        command: ["bash", "-c", "--"]
        args: ["while :; do sh /appstore/deletelogs/log_compress.sh; sleep 300; done;"]
        volumeMounts:
          - name: appstore-logs
            mountPath: /appstore/writable/logs
          - name: appstore-debugbar
            mountPath: /appstore/writable/debugbar
          - name: smplapp1-delete-logs-scripts
            mountPath: /appstore/deletelogs

      # Pod shared volumes
      volumes:
      - name: fpm-shared
        emptyDir: {}
      - name: appstore-logs
        emptyDir: {}
      - name: appstore-debugbar
        emptyDir: {}
      - name: smplapp1-fb-config
        configMap:
          name: smplapp1-cm-fb-config
      - name: smplapp1-delete-logs-scripts
        configMap:
          name: smplapp1-cm-delete-logs-scripts
          items:
          - key: log_compress.sh
            path: log_compress.sh
            mode: 0755
          - key: log_compress.conf
            path: log_compress.conf
            mode: 0644




      #podMetadata:
      #  labels:
      #    owner: infra
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: "app.kubernetes.io/name"
                operator: In
                values:
                - "smplapp1"
            topologyKey: "kubernetes.io/hostname"

      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: smplapp1

---
apiVersion: v1
kind: Service
metadata:
  name: smplapp1
  namespace: smplapp
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: smplapp1

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: smplapp1-cm-fb-config
  namespace: smplapp
data:
  fluent-bit.conf: |- 
    [SERVICE]
      Config_Watch      On
      Flush             1
      Grace             5
      Daemon            Off
      Log_Level         info
      Parsers_File      /fluent-bit/etc/parsers.conf
      HTTP_Server       Off
      Hot_Reload        On
      Storage.Path      /appstore/fb-storage
      Storage.Backlog.Mem_Limit 100MB

    [INPUT]
      Name              tail
      Buffer_Max_Size   64k
      Mem_Buf_Limit     10MB
      Path              /appstore/writable/logs/*.log,/appstore/writable/logs/**/*.log,/appstore/writable/logs/**/**/*.log
      Path_Key          filepath
      #Parser            codeigniter
      Tag               smplapp1
      Ignore_Older      2d
      Db                /appstore/logs.db

    #[FILTER]
    #  Name              parser
    #  Match             *
    #  Key_Name          filepath
    #  Parser            codeigniter_timeparser
    #  Parser            filepath_extractor
    #  Preserve_Key      On
    #  Reserve_Data      On

    [OUTPUT]
      Name              stdout
      Match             *
    [OUTPUT]
      Name              loki
      Match             *
      Host              loki-gateway.logbase.svc.cluster.local
      port              80
      labels            job=fluentbit,app=smplapp1,filepath=$filepath
      auto_kubernetes_labels On
      line_format       json

  parsers.conf: |-
    [PARSER]
      Name              filepath_extractor
      Format            regex
      Regex             ^(?<filepath>.*)$
    [PARSER]
      Name              codeigniter_timeparser

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: smplapp1-cm-delete-logs-scripts
  namespace: smplapp
data:
  log_compress.conf: |-
    # test
  log_compress.sh: |-
    #!/bin/bash
    # delete logs older than 1 days
    #find /appstore/writable -type f -mtime +1 -exec rm -f {} \;
    find /appstore/writable/debugbar -type f -mmin +60 -exec rm -f {} \;
    find /appstore/writable/logs -type f -mtime +1 -exec rm -f {} \;
    exit $?

