##### for local cluster
replicaCount: 1

autoscaling:
  enabled: false

strategy:
  rollingUpdate:
    maxUnavailable: 0  #for replica 1 rollingupdate

phpfpm:
  image:
    repository: harbor.dh1.div1.opendoor.local/smplapp-a/app-otel
    tag: "latest"
    pullPolicy: Always
  env:
    dev_enabled: "1"
    xdebug_enabled: "0"
    app_jhotel_dbhost: "p-ts-schdb25.div1.opendoor.local"
    app_jhotel_dbport: "5432"
    app_jhotel_dbname: "ref_jhotel"
    app_jhotel_dbuser: "ref_jhotel_ref"
    app_jhotel_dbpass: "ref_jhotel_ref8707"

  resources:
    requests:
      memory: "128Mi"
      cpu: "10m"
    limits:
      memory: "1024Mi"
      cpu: "2000m"

nginx:
  image:
    repository: harbor.dh1.div1.opendoor.local/smplapp-a/web-otel
    tag: "latest"
    pullPolicy: Always
  env:
    fastcgi_params_addfile: "fastcgi_params-codeigniter-development"
  resources:
    requests:
      memory: "64Mi"
      cpu: "10m"
    limits:
      memory: "128Mi"
      cpu: "500m"

sidecar:
  fluentBit:
    enabled: true
    image:
      repository: harbor.dh1.div1.opendoor.local/hub.docker.com/fluent/fluent-bit
      #tag: "3.1.10-debug"
      #tag: "3.1.10"
      pullPolicy: IfNotPresent

  helper:
    enabled: true

# disable podAntiAffinity for single replica
affinity:
  podAntiAffinity:

gateways:
  enabled: true
  httproutes:
    priv:
      enabled: true
      hostnames: ["smplapp.priv.local-k8s.div1.opendoor.local"]

