##### for local cluster development
replicaCount: 1

autoscaling:
  enabled: false

strategy:
  rollingUpdate:
    maxUnavailable: 0  #for replica 1 rollingupdate

phpfpm:
  image:
    repository: harbor.dh1.div1.opendoor.local/smplapp-a/app-otel
    tag: "latest"
    pullPolicy: Always
  env:
    dev_enabled: "1"
    xdebug_enabled: "0"
    xdebug_client_host: "host.k3d.internal"
    xdebug_client_port: "9003"
    app_jhotel_dbhost: "p-ts-schdb25.div1.opendoor.local"
    app_jhotel_dbport: "5432"
    app_jhotel_dbname: "ref_jhotel"
    app_jhotel_dbuser: "ref_jhotel_ref"
    app_jhotel_dbpass: "ref_jhotel_ref8707"
  resources:
    requests:
      memory: "128Mi"
      cpu: "10m"
    limits:
      memory: "1024Mi"
      cpu: "2000m"
  volumeMounts:
  - name: fpm-shared
    mountPath: /var/run/php-fpm
  - name: webapp
    mountPath: /var/www/webapp
  - name: xdebug
    mountPath: /tmp/xdebug

nginx:
  image:
    repository: harbor.dh1.div1.opendoor.local/smplapp-a/web-otel
    tag: "latest"
    pullPolicy: Always
  env:
    fastcgi_params_addfile: "fastcgi_params-codeigniter-development"
  resources:
    requests:
      memory: "64Mi"
      cpu: "10m"
    limits:
      memory: "128Mi"
      cpu: "500m"
  volumeMounts:
  - name: fpm-shared
    mountPath: /var/run/php-fpm
  - name: webapp-public
    mountPath: /var/www/public

sidecar:
  fluentBit:
    enabled: true
    image:
      repository: harbor.dh1.div1.opendoor.local/hub.docker.com/fluent/fluent-bit
      #tag: "3.1.10-debug"
      #tag: "3.1.10"
      pullPolicy: IfNotPresent
    volumeMounts:
    - name: webapp
      mountPath: /appstore/writable/logs
      subPath: writable/logs
    - name: fluentbit-config
      mountPath: /fluent-bit/etc

  helper:
    enabled: true
    volumeMounts:
    - name: webapp
      mountPath: /appstore/writable/logs
      subPath: writable/logs
    - name: webapp
      mountPath: /appstore/writable/debugbar
      subPath: writable/debugbar
    - name: delete-logs-scripts
      mountPath: /appstore/deletelogs

volumes:
- name: fpm-shared
  emptyDir: {}
- name: webapp
  hostPath:
    path: /data/pv/k8s-smplapp-otel/webapp
    type: Directory
- name: xdebug
  hostPath:
    path: /data/pv/k8s-smplapp-otel/xdebug
    type: Directory
- name: webapp-public
  hostPath:
    path: /data/pv/k8s-smplapp-otel/webapp/public
    type: Directory
- name: fluentbit-config
  configMap:
    name: cm-fluentbit-config
- name: delete-logs-scripts
  configMap:
    name: cm-delete-logs-scripts
    items:
    - key: log_compress.sh
      path: log_compress.sh
      mode: 0755
    - key: log_compress.conf
      path: log_compress.conf
      mode: 0644

# disable podAntiAffinity for single replica
affinity:
  podAntiAffinity:

gateways:
  enabled: true
  httproutes:
    priv:
      enabled: true
      hostnames: ["smplapp.priv.local-k8s.div1.opendoor.local"]

