replicaCount: 1

autoscaling:
  enabled: false

strategy:
  rollingUpdate:
    maxUnavailable: 0  #for replica 1 rollingupdate

phpfpm:
  image:
    repository: harbor.dh1.div1.opendoor.local/smplapp-a/app-otel
    tag: "latest"
    pullPolicy: Always
  extraEnv:
  - name: XDEBUG_ENABLED
    value: "0"
  - name: DEV_ENABLED
    value: "1"
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "1024Mi"
      cpu: "2000m"

nginx:
  image:
    repository: harbor.dh1.div1.opendoor.local/smplapp-a/web-otel
    tag: "latest"
    pullPolicy: Always
  extaEnv:
  - name: FASTCGI_PARAMS_ADDFILE
    value: fastcgi_params-codeigniter-development
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "500m"

sidecar:
  fluentBit:
    enabled: true
    image:
      repository: harbor.dh1.div1.opendoor.local/hub.docker.com/fluent/fluent-bit
      #tag: "3.0.7-debug"
      tag: "3.0.7"
      pullPolicy: IfNotPresent

  helper:
    enabled: true

# disable podAntiAffinity for single replica
affinity:
  podAntiAffinity:

configMaps:
- name: cm-fluentbit-config
  data:
    fluent-bit.conf: |-
      [SERVICE]
        Config_Watch      On
        Flush             1
        Grace             5
        Daemon            Off
        Log_Level         info
        Parsers_File      /fluent-bit/etc/parsers.conf
        HTTP_Server       Off
        Hot_Reload        On
        Storage.Path      /appstore/fb-storage
        Storage.Backlog.Mem_Limit 100MB
      
      [INPUT]
        Name              tail
        Buffer_Max_Size   64k
        Mem_Buf_Limit     10MB
        Path              /appstore/writable/logs/*.log,/appstore/writable/logs/**/*.log,/appstore/writable/logs/**/**/*.log
        Path_Key          filepath
        #Parser            codeigniter
        Tag               smplapp
        Ignore_Older      2d
        Db                /appstore/logs.db
      
      #[FILTER]
      #  Name              parser
      #  Match             *
      #  Key_Name          filepath
      #  Parser            codeigniter_timeparser
      #  Parser            filepath_extractor
      #  Preserve_Key      On
      #  Reserve_Data      On
      
      [OUTPUT]
        Name              stdout
        Match             *
      [OUTPUT]
        Name              loki
        Match             *
        Host              loki.logbase.svc.cluster.local
        port              3100
        labels            job=fluentbit,app=smplapp,filepath=$filepath
        auto_kubernetes_labels On
        line_format       json
      
    parsers.conf: |-
      [PARSER]
        Name              filepath_extractor
        Format            regex
        Regex             ^(?<filepath>.*)$
      [PARSER]
        Name              codeigniter_timeparser

- name: cm-delete-logs-scripts
  data:
    log_compress.conf: |-
      # Configuration file for log_compress.sh
    log_compress.sh: |-
      #!/bin/bash
      # delete logs older than 1 days
      #find /appstore/writable -type f -mtime +1 -exec rm -f {} \;
      find /appstore/writable/debugbar -type f -mmin +60 -exec rm -f {} \;
      find /appstore/writable/logs -type f -mtime +1 -exec rm -f {} \;
      exit $?

gateways:
  enabled: true
  hostnames: ["smplapp.priv.local-k8s.div1.opendoor.local"]
